os: linux
dist: bionic
language: generic
env:
  - CODACY_PROJECT_TOKEN=71fa15314d644b95a9acda57768469b1
after_sucess:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info